title: Nothing to see here
description: Go away
show_downloads: false
theme: jekyll-theme-cayman
include: [".well-known", "assets"]
github:
  is_project_page: true
  repository_url: https://github.com/Textic/textic.github.io